// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMGrg3G725_bKe7xyABFsN0cAhWdPeE7g',
    appId: '1:29620907509:web:cf0d53f9e22af9f5d804bc',
    messagingSenderId: '29620907509',
    projectId: 'chatwith-3a812',
    authDomain: 'chatwith-3a812.firebaseapp.com',
    storageBucket: 'chatwith-3a812.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnQydThRb-pRG78B0u0PY-s9VoF0JmXPQ',
    appId: '1:29620907509:android:d6f4a603912a6571d804bc',
    messagingSenderId: '29620907509',
    projectId: 'chatwith-3a812',
    storageBucket: 'chatwith-3a812.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkWD3g6s-7AERth6DqhjZU0PgU1VHHgRo',
    appId: '1:29620907509:ios:6246f53bb4ec7519d804bc',
    messagingSenderId: '29620907509',
    projectId: 'chatwith-3a812',
    storageBucket: 'chatwith-3a812.firebasestorage.app',
    iosBundleId: 'com.projects.chatwith',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkWD3g6s-7AERth6DqhjZU0PgU1VHHgRo',
    appId: '1:29620907509:ios:6246f53bb4ec7519d804bc',
    messagingSenderId: '29620907509',
    projectId: 'chatwith-3a812',
    storageBucket: 'chatwith-3a812.firebasestorage.app',
    iosBundleId: 'com.projects.chatwith',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMGrg3G725_bKe7xyABFsN0cAhWdPeE7g',
    appId: '1:29620907509:web:f773a7fdd127ba94d804bc',
    messagingSenderId: '29620907509',
    projectId: 'chatwith-3a812',
    authDomain: 'chatwith-3a812.firebaseapp.com',
    storageBucket: 'chatwith-3a812.firebasestorage.app',
  );
}
